# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

TournamentType.create(tournament_type: 'INDIVIDUAL')
TournamentType.create(tournament_type: 'TEAM SCRAMBLE')
#TournamentType.create(tournament_type: 'TEAM')
tt = TournamentType.create(tournament_type: 'TWO-TEAM')

RoundType.create(round_type: '2-BALL')
RoundType.create(round_type: '4-BALL')
RoundType.create(round_type: 'HEAD-TO-HEAD')

fresca2012 = tt.tournaments.create(title: 'FRESCA 2012', subtitle: '', tournament_date: '6/1/2012', location: 'Pebble Beach', handicap: true, male_players: true, female_players: false, started: true, complete: true)
fresca2012.teams.create(name: 'Unnamed', team_number: 1)
fresca2012.teams.create(name: 'Unnamed', team_number: 2)

fresca2013 = tt.tournaments.create(title: 'FRESCA 2013', subtitle: 'Pining for You', tournament_date: '6/1/2013', location: 'Torrey Pines', handicap: true, male_players: true, female_players: false, started: true, complete: false)
fresca2013.teams.create(name: 'Unnamed', team_number: 1)
fresca2013.teams.create(name: 'Unnamed', team_number: 2)

fresca2014 = tt.tournaments.create(title: 'FRESCA 2014', subtitle: 'Birdies and Bogies', tournament_date: '6/1/2014', location: 'Bandon Dunes', handicap: true, male_players: true, female_players: false, started: false, complete: false)
fresca2014.teams.create(name: 'Unnamed', team_number: 1)
fresca2014.teams.create(name: 'Unnamed', team_number: 2)

Player.create(first_name: 'Jamie', last_name: 'Gulick', nickname: 'Lurch', handicap: 24.7, email: 'jamie.gulick@gmail.com', username: 'jamie.gulick@gmail.com', password: 'password')
Player.create(first_name: 'Brian', last_name: 'Cordyack', nickname: 'Yack', handicap: 19.2, email: 'username@server.com', username: 'bcordyack', password: 'password')
Player.create(first_name: 'Dan', last_name: 'Shomaker', nickname: 'Shomo', handicap: 13.3, email: 'username@server.com', username: 'dshomaker', password: 'password')
Player.create(first_name: 'Jeff', last_name: 'Hall', nickname: 'Jefe', handicap: 10, email: 'username@server.com', username: 'jhall', password: 'password')
Player.create(first_name: 'Matt', last_name: 'Foster', nickname: 'Fos', handicap: 7.3, email: 'username@server.com', username: 'mfoster', password: 'password')
Player.create(first_name: 'Chris', last_name: 'Hawkins', nickname: 'CHawk', handicap: 29.4, email: 'username@server.com', username: 'chawkins', password: 'password')
Player.create(first_name: 'Greg', last_name: 'Bane', nickname: 'Bane', handicap: 20.5, email: 'username@server.com', username: 'gbane', password: 'password')
Player.create(first_name: 'Michael', last_name: 'Belinkie', handicap: 31.7, email: 'username@server.com', username: 'mbelinkie', password: 'password')
Player.create(first_name: 'Matt', last_name: 'Zalubowski', nickname: 'Zow', handicap: 19.2, email: 'username@server.com', username: 'mzalubowski', password: 'password')
Player.create(first_name: 'Jason', last_name: 'Elam', handicap: 23, email: 'username@server.com', username: 'jelam', password: 'password')
Player.create(first_name: '11', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player11', password: 'password')
Player.create(first_name: '12', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player12', password: 'password')
Player.create(first_name: '13', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player13', password: 'password')
Player.create(first_name: '14', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player14', password: 'password')
Player.create(first_name: '15', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player15', password: 'password')
Player.create(first_name: '16', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player16', password: 'password')
Player.create(first_name: '17', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player17', password: 'password')
Player.create(first_name: '18', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player18', password: 'password')
Player.create(first_name: '19', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player19', password: 'password')
Player.create(first_name: '20', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player20', password: 'password')

mens = TeeBoxType.create(tee_box_type: 'MENS')
ladies = TeeBoxType.create(tee_box_type: 'LADIES')
both = TeeBoxType.create(tee_box_type: 'BOTH')

gc = Course.create(name: 'Goose Creek Golf Club', phone_number: '(703) 729-2500', address: '43001 Golf Club Road', city: 'Leesburg', state: 'VA', zip: '20175', par3: false)
gcblue = gc.tee_boxes.create(color: 'BLUE', mens_course_rating: 71.8, mens_course_slope: 130, ladies_course_rating: 71.8, ladies_course_slope: 130, tee_box_type_id: mens.id, total_yardage_dirty: 6410)
gcblue.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 475, handicap_mens: 3, handicap_ladies:3)
gcblue.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 387, handicap_mens: 9, handicap_ladies: 9)
gcblue.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 169, handicap_mens: 11, handicap_ladies: 11)
gcblue.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 377, handicap_mens: 13, handicap_ladies: 13)
gcblue.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 376, handicap_mens: 5, handicap_ladies: 5)
gcblue.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 411, handicap_mens: 1, handicap_ladies: 1)
gcblue.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 308, handicap_mens: 17, handicap_ladies: 17)
gcblue.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 322, handicap_mens: 15, handicap_ladies: 15)
gcblue.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 193, handicap_mens: 7, handicap_ladies: 7)
gcblue.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 329, handicap_mens: 16, handicap_ladies: 16)
gcblue.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 429, handicap_mens: 4, handicap_ladies: 4)
gcblue.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 417, handicap_mens: 2, handicap_ladies: 2)
gcblue.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 236, handicap_mens: 10, handicap_ladies: 10)
gcblue.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 496, handicap_mens: 14, handicap_ladies: 14)
gcblue.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 494, handicap_mens: 12, handicap_ladies: 12)
gcblue.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 227, handicap_mens: 6, handicap_ladies: 6)
gcblue.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 425, handicap_mens: 8, handicap_ladies: 8)
gcblue.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 339, handicap_mens: 18, handicap_ladies: 18)

gcwhite = gc.tee_boxes.create(color: 'WHITE', mens_course_rating: 69.6, mens_course_slope: 125, ladies_course_rating: 69.6, ladies_course_slope: 125, tee_box_type_id: mens.id, total_yardage_dirty: 5937)
gcwhite.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 471, handicap_mens: 3, handicap_ladies:3)
gcwhite.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 366, handicap_mens: 9, handicap_ladies: 9)
gcwhite.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 143, handicap_mens: 11, handicap_ladies: 11)
gcwhite.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 346, handicap_mens: 13, handicap_ladies: 13)
gcwhite.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 370, handicap_mens: 5, handicap_ladies: 5)
gcwhite.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 393, handicap_mens: 1, handicap_ladies: 1)
gcwhite.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 279, handicap_mens: 17, handicap_ladies: 17)
gcwhite.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 297, handicap_mens: 15, handicap_ladies: 15)
gcwhite.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 155, handicap_mens: 7, handicap_ladies: 7)
gcwhite.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 321, handicap_mens: 16, handicap_ladies: 16)
gcwhite.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 410, handicap_mens: 4, handicap_ladies: 4)
gcwhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 2, handicap_ladies: 2)
gcwhite.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 189, handicap_mens: 10, handicap_ladies: 10)
gcwhite.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 449, handicap_mens: 14, handicap_ladies: 14)
gcwhite.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 484, handicap_mens: 12, handicap_ladies: 12)
gcwhite.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 182, handicap_mens: 6, handicap_ladies: 6)
gcwhite.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 8, handicap_ladies: 8)
gcwhite.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 332, handicap_mens: 18, handicap_ladies: 18)

gcred = gc.tee_boxes.create(color: 'RED', mens_course_rating: 70.7, mens_course_slope: 123, ladies_course_rating: 70.7, ladies_course_slope: 123, tee_box_type_id: ladies.id, total_yardage_dirty: 5170)
gcred.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 391, handicap_mens: 9, handicap_ladies:9)
gcred.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 324, handicap_mens: 3, handicap_ladies: 3)
gcred.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 111, handicap_mens: 17, handicap_ladies: 17)
gcred.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 323, handicap_mens: 1, handicap_ladies: 1)
gcred.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 335, handicap_mens: 7, handicap_ladies: 7)
gcred.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 292, handicap_mens: 5, handicap_ladies: 5)
gcred.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 272, handicap_mens: 15, handicap_ladies: 15)
gcred.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 244, handicap_mens: 13, handicap_ladies: 13)
gcred.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 144, handicap_mens: 11, handicap_ladies: 11)
gcred.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 270, handicap_mens: 14, handicap_ladies: 14)
gcred.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 350, handicap_mens: 2, handicap_ladies: 2)
gcred.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 312, handicap_mens: 6, handicap_ladies: 6)
gcred.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 155, handicap_mens: 16, handicap_ladies: 16)
gcred.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 428, handicap_mens: 10, handicap_ladies: 10)
gcred.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 433, handicap_mens: 8, handicap_ladies: 8)
gcred.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 159, handicap_mens: 12, handicap_ladies: 12)
gcred.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 308, handicap_mens: 4, handicap_ladies: 4)
gcred.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 319, handicap_mens: 18, handicap_ladies: 18)

t = Course.create(name: 'Trilogy Golf Club at Power Ranch', phone_number: '(480) 988-5956', address: '4415 East Village Parkway', city: 'Gilbert', state: 'AZ', zip: '85297', par3: false)

tblack = t.tee_boxes.create(color: 'BLACK', mens_course_rating: 71.5, mens_course_slope: 130, ladies_course_rating: 71.5, ladies_course_slope: 130, tee_box_type_id: mens.id, total_yardage_dirty: 6932)
tblack.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 14, handicap_ladies:14)
tblack.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 16, handicap_ladies: 16)
tblack.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 605, handicap_mens: 2, handicap_ladies: 2)
tblack.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 180, handicap_mens: 18, handicap_ladies: 18)
tblack.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 394, handicap_mens: 10, handicap_ladies: 10)
tblack.holes.create(hole_number: 6, par_mens: 3, par_ladies: 3, yardage: 191, handicap_mens: 12, handicap_ladies: 12)
tblack.holes.create(hole_number: 7, par_mens: 5, par_ladies: 5, yardage: 620, handicap_mens: 4, handicap_ladies: 4)
tblack.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 210, handicap_mens: 8, handicap_ladies: 8)
tblack.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 420, handicap_mens: 6, handicap_ladies: 6)
tblack.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 374, handicap_mens: 13, handicap_ladies: 13)
tblack.holes.create(hole_number: 11, par_mens: 3, par_ladies: 3, yardage: 185, handicap_mens: 15, handicap_ladies: 15)
tblack.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 400, handicap_mens: 11, handicap_ladies: 11)
tblack.holes.create(hole_number: 13, par_mens: 5, par_ladies: 5, yardage: 557, handicap_mens: 7, handicap_ladies: 7)
tblack.holes.create(hole_number: 14, par_mens: 4, par_ladies: 4, yardage: 430, handicap_mens: 9, handicap_ladies: 9)
tblack.holes.create(hole_number: 15, par_mens: 3, par_ladies: 3, yardage: 195, handicap_mens: 17, handicap_ladies: 17)
tblack.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 450, handicap_mens: 1, handicap_ladies: 1)
tblack.holes.create(hole_number: 17, par_mens: 5, par_ladies: 5, yardage: 558, handicap_mens: 3, handicap_ladies: 3)
tblack.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 413, handicap_mens: 5, handicap_ladies: 5)

tblue = t.tee_boxes.create(color: 'BLUE', mens_course_rating: 69.0, mens_course_slope: 122, ladies_course_rating: 69.0, ladies_course_slope: 122, tee_box_type_id: mens.id, total_yardage_dirty: 6375)
tblue.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 349, handicap_mens: 14, handicap_ladies:14)
tblue.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 313, handicap_mens: 16, handicap_ladies: 16)
tblue.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 580, handicap_mens: 2, handicap_ladies: 2)
tblue.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 157, handicap_mens: 18, handicap_ladies: 18)
tblue.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 364, handicap_mens: 10, handicap_ladies: 10)
tblue.holes.create(hole_number: 6, par_mens: 3, par_ladies: 3, yardage: 190, handicap_mens: 12, handicap_ladies: 12)
tblue.holes.create(hole_number: 7, par_mens: 5, par_ladies: 5, yardage: 596, handicap_mens: 4, handicap_ladies: 4)
tblue.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 208, handicap_mens: 8, handicap_ladies: 8)
tblue.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 6, handicap_ladies: 6)
tblue.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 359, handicap_mens: 13, handicap_ladies: 13)
tblue.holes.create(hole_number: 11, par_mens: 3, par_ladies: 3, yardage: 169, handicap_mens: 15, handicap_ladies: 15)
tblue.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 360, handicap_mens: 11, handicap_ladies: 11)
tblue.holes.create(hole_number: 13, par_mens: 5, par_ladies: 5, yardage: 508, handicap_mens: 7, handicap_ladies: 7)
tblue.holes.create(hole_number: 14, par_mens: 4, par_ladies: 4, yardage: 373, handicap_mens: 9, handicap_ladies: 9)
tblue.holes.create(hole_number: 15, par_mens: 3, par_ladies: 3, yardage: 157, handicap_mens: 17, handicap_ladies: 17)
tblue.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 419, handicap_mens: 1, handicap_ladies: 1)
tblue.holes.create(hole_number: 17, par_mens: 5, par_ladies: 5, yardage: 525, handicap_mens: 3, handicap_ladies: 3)
tblue.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 373, handicap_mens: 5, handicap_ladies: 5)

twhite = t.tee_boxes.create(color: 'WHITE', mens_course_rating: 66.5, mens_course_slope: 112, ladies_course_rating: 71.8, ladies_course_slope: 131, tee_box_type_id: both.id, total_yardage_dirty: 5677)
twhite.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 311, handicap_mens: 14, handicap_ladies:14)
twhite.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 276, handicap_mens: 16, handicap_ladies: 16)
twhite.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 502, handicap_mens: 2, handicap_ladies: 2)
twhite.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 122, handicap_mens: 18, handicap_ladies: 18)
twhite.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 331, handicap_mens: 10, handicap_ladies: 10)
twhite.holes.create(hole_number: 6, par_mens: 3, par_ladies: 3, yardage: 158, handicap_mens: 12, handicap_ladies: 12)
twhite.holes.create(hole_number: 7, par_mens: 5, par_ladies: 5, yardage: 494, handicap_mens: 4, handicap_ladies: 4)
twhite.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 160, handicap_mens: 8, handicap_ladies: 8)
twhite.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 336, handicap_mens: 6, handicap_ladies: 6)
twhite.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 328, handicap_mens: 13, handicap_ladies: 13)
twhite.holes.create(hole_number: 11, par_mens: 3, par_ladies: 3, yardage: 148, handicap_mens: 15, handicap_ladies: 15)
twhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 322, handicap_mens: 11, handicap_ladies: 11)
twhite.holes.create(hole_number: 13, par_mens: 5, par_ladies: 5, yardage: 487, handicap_mens: 7, handicap_ladies: 7)
twhite.holes.create(hole_number: 14, par_mens: 4, par_ladies: 4, yardage: 348, handicap_mens: 9, handicap_ladies: 9)
twhite.holes.create(hole_number: 15, par_mens: 3, par_ladies: 3, yardage: 150, handicap_mens: 17, handicap_ladies: 17)
twhite.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 385, handicap_mens: 1, handicap_ladies: 1)
twhite.holes.create(hole_number: 17, par_mens: 5, par_ladies: 5, yardage: 480, handicap_mens: 3, handicap_ladies: 3)
twhite.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 339, handicap_mens: 5, handicap_ladies: 5)

tred = t.tee_boxes.create(color: 'RED', mens_course_rating: 67.9, mens_course_slope: 120, ladies_course_rating: 67.9, ladies_course_slope: 120, tee_box_type_id: ladies.id, total_yardage_dirty: 4918)
tred.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 281, handicap_mens: 8, handicap_ladies:8)
tred.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 239, handicap_mens: 18, handicap_ladies: 18)
tred.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 453, handicap_mens: 4, handicap_ladies: 4)
tred.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 104, handicap_mens: 14, handicap_ladies: 14)
tred.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 279, handicap_mens: 10, handicap_ladies: 10)
tred.holes.create(hole_number: 6, par_mens: 3, par_ladies: 3, yardage: 120, handicap_mens: 16, handicap_ladies: 16)
tred.holes.create(hole_number: 7, par_mens: 5, par_ladies: 5, yardage: 460, handicap_mens: 2, handicap_ladies: 2)
tred.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 131, handicap_mens: 12, handicap_ladies: 12)
tred.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 268, handicap_mens: 6, handicap_ladies: 6)
tred.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 287, handicap_mens: 15, handicap_ladies: 15)
tred.holes.create(hole_number: 11, par_mens: 3, par_ladies: 3, yardage: 113, handicap_mens: 17, handicap_ladies: 17)
tred.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 281, handicap_mens: 13, handicap_ladies: 13)
tred.holes.create(hole_number: 13, par_mens: 5, par_ladies: 5, yardage: 433, handicap_mens: 7, handicap_ladies: 7)
tred.holes.create(hole_number: 14, par_mens: 4, par_ladies: 4, yardage: 309, handicap_mens: 3, handicap_ladies: 3)
tred.holes.create(hole_number: 15, par_mens: 3, par_ladies: 3, yardage: 115, handicap_mens: 11, handicap_ladies: 11)
tred.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 310, handicap_mens: 1, handicap_ladies: 1)
tred.holes.create(hole_number: 17, par_mens: 5, par_ladies: 5, yardage: 444, handicap_mens: 5, handicap_ladies: 5)
tred.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 291, handicap_mens: 9, handicap_ladies: 9)

dm = Course.create(name: 'Dinosaur Mountain at Gold Canyon Golf Resort', phone_number: '(800) 827-5281', address: '6100 S Kings Ranch Rd', city: 'Gold Canyon', state: 'AZ', zip: '85118', par3: false)
dmgold = dm.tee_boxes.create(color: 'GOLD', mens_course_rating: 71.5, mens_course_slope: 144, ladies_course_rating: 71.5, ladies_course_slope: 144, tee_box_type_id: mens.id, total_yardage_dirty: 0)
dmgold.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 316, handicap_mens: 15, handicap_ladies:15)
dmgold.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 197, handicap_mens: 11, handicap_ladies: 11)
dmgold.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 514, handicap_mens: 1, handicap_ladies: 1)
dmgold.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 467, handicap_mens: 3, handicap_ladies: 3)
dmgold.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 235, handicap_mens: 13, handicap_ladies: 13)
dmgold.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 451, handicap_mens: 9, handicap_ladies: 9)
dmgold.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 439, handicap_mens: 7, handicap_ladies: 7)
dmgold.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 203, handicap_mens: 17, handicap_ladies: 17)
dmgold.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 542, handicap_mens: 5, handicap_ladies: 5)
dmgold.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 170, handicap_mens: 18, handicap_ladies: 18)
dmgold.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 543, handicap_mens: 10, handicap_ladies: 10)
dmgold.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 448, handicap_mens: 4, handicap_ladies: 4)
dmgold.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 454, handicap_mens: 2, handicap_ladies: 2)
dmgold.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 226, handicap_mens: 6, handicap_ladies: 6)
dmgold.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 378, handicap_mens: 14, handicap_ladies: 14)
dmgold.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 535, handicap_mens: 8, handicap_ladies: 8)
dmgold.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 168, handicap_mens: 16, handicap_ladies: 16)
dmgold.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 366, handicap_mens: 12, handicap_ladies: 12)

dmblack = dm.tee_boxes.create(color: 'BLACK', mens_course_rating: 69.5, mens_course_slope: 136, ladies_course_rating: 69.5, ladies_course_slope: 136, tee_box_type_id: mens.id, total_yardage_dirty: 0)
dmblack.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 305, handicap_mens: 15, handicap_ladies:15)
dmblack.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 188, handicap_mens: 11, handicap_ladies: 11)
dmblack.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 495, handicap_mens: 1, handicap_ladies: 1)
dmblack.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 452, handicap_mens: 3, handicap_ladies: 3)
dmblack.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 223, handicap_mens: 13, handicap_ladies: 13)
dmblack.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 435, handicap_mens: 9, handicap_ladies: 9)
dmblack.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 419, handicap_mens: 7, handicap_ladies: 7)
dmblack.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 191, handicap_mens: 17, handicap_ladies: 17)
dmblack.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 535, handicap_mens: 5, handicap_ladies: 5)
dmblack.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 152, handicap_mens: 18, handicap_ladies: 18)
dmblack.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 517, handicap_mens: 10, handicap_ladies: 10)
dmblack.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 427, handicap_mens: 4, handicap_ladies: 4)
dmblack.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 420, handicap_mens: 2, handicap_ladies: 2)
dmblack.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 201, handicap_mens: 6, handicap_ladies: 6)
dmblack.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 365, handicap_mens: 14, handicap_ladies: 14)
dmblack.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 510, handicap_mens: 8, handicap_ladies: 8)
dmblack.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 148, handicap_mens: 16, handicap_ladies: 16)
dmblack.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 339, handicap_mens: 12, handicap_ladies: 12)

dmblue = dm.tee_boxes.create(color: 'BLUE', mens_course_rating: 66.9, mens_course_slope: 124, ladies_course_rating: 66.9, ladies_course_slope: 124, tee_box_type_id: mens.id, total_yardage_dirty: 0)
dmblue.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 300, handicap_mens: 15, handicap_ladies:15)
dmblue.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 174, handicap_mens: 11, handicap_ladies: 11)
dmblue.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 465, handicap_mens: 1, handicap_ladies: 1)
dmblue.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 408, handicap_mens: 3, handicap_ladies: 3)
dmblue.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 199, handicap_mens: 13, handicap_ladies: 13)
dmblue.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 409, handicap_mens: 9, handicap_ladies: 9)
dmblue.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 355, handicap_mens: 7, handicap_ladies: 7)
dmblue.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 148, handicap_mens: 17, handicap_ladies: 17)
dmblue.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 514, handicap_mens: 5, handicap_ladies: 5)
dmblue.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 142, handicap_mens: 18, handicap_ladies: 18)
dmblue.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 463, handicap_mens: 10, handicap_ladies: 10)
dmblue.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 381, handicap_mens: 4, handicap_ladies: 4)
dmblue.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 384, handicap_mens: 2, handicap_ladies: 2)
dmblue.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 179, handicap_mens: 6, handicap_ladies: 6)
dmblue.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 354, handicap_mens: 14, handicap_ladies: 14)
dmblue.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 464, handicap_mens: 8, handicap_ladies: 8)
dmblue.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 138, handicap_mens: 16, handicap_ladies: 16)
dmblue.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 319, handicap_mens: 12, handicap_ladies: 12)

dmwhite = dm.tee_boxes.create(color: 'WHITE', mens_course_rating: 65.0, mens_course_slope: 116, ladies_course_rating: 71.1, ladies_course_slope: 128, tee_box_type_id: both.id, total_yardage_dirty: 0)
dmwhite.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 271, handicap_mens: 15, handicap_ladies:15)
dmwhite.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 150, handicap_mens: 11, handicap_ladies: 11)
dmwhite.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 418, handicap_mens: 1, handicap_ladies: 1)
dmwhite.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 372, handicap_mens: 3, handicap_ladies: 3)
dmwhite.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 170, handicap_mens: 13, handicap_ladies: 13)
dmwhite.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 378, handicap_mens: 9, handicap_ladies: 9)
dmwhite.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 335, handicap_mens: 7, handicap_ladies: 7)
dmwhite.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 130, handicap_mens: 17, handicap_ladies: 17)
dmwhite.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 490, handicap_mens: 5, handicap_ladies: 5)
dmwhite.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 136, handicap_mens: 18, handicap_ladies: 18)
dmwhite.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 453, handicap_mens: 10, handicap_ladies: 10)
dmwhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 346, handicap_mens: 4, handicap_ladies: 4)
dmwhite.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 343, handicap_mens: 2, handicap_ladies: 2)
dmwhite.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 143, handicap_mens: 6, handicap_ladies: 6)
dmwhite.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 340, handicap_mens: 14, handicap_ladies: 14)
dmwhite.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 436, handicap_mens: 8, handicap_ladies: 8)
dmwhite.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 116, handicap_mens: 16, handicap_ladies: 16)
dmwhite.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 310, handicap_mens: 12, handicap_ladies: 12)

dmsilver = dm.tee_boxes.create(color: 'SILVER', mens_course_rating: 64.1, mens_course_slope: 114, ladies_course_rating: 69.7, ladies_course_slope: 125, tee_box_type_id: both.id, total_yardage_dirty: 0)
dmsilver.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 259, handicap_mens: 15, handicap_ladies:15)
dmsilver.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 143, handicap_mens: 11, handicap_ladies: 11)
dmsilver.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 422, handicap_mens: 1, handicap_ladies: 1)
dmsilver.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 330, handicap_mens: 3, handicap_ladies: 3)
dmsilver.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 165, handicap_mens: 13, handicap_ladies: 13)
dmsilver.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 372, handicap_mens: 9, handicap_ladies: 9)
dmsilver.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 341, handicap_mens: 7, handicap_ladies: 7)
dmsilver.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 130, handicap_mens: 17, handicap_ladies: 17)
dmsilver.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 459, handicap_mens: 5, handicap_ladies: 5)
dmsilver.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 129, handicap_mens: 18, handicap_ladies: 18)
dmsilver.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 421, handicap_mens: 10, handicap_ladies: 10)
dmsilver.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 347, handicap_mens: 4, handicap_ladies: 4)
dmsilver.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 331, handicap_mens: 2, handicap_ladies: 2)
dmsilver.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 141, handicap_mens: 6, handicap_ladies: 6)
dmsilver.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 331, handicap_mens: 14, handicap_ladies: 14)
dmsilver.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 410, handicap_mens: 8, handicap_ladies: 8)
dmsilver.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 116, handicap_mens: 16, handicap_ladies: 16)
dmsilver.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 301, handicap_mens: 12, handicap_ladies: 12)

dmred = dm.tee_boxes.create(color: 'RED', mens_course_rating: 67.2, mens_course_slope: 119, ladies_course_rating: 67.2, ladies_course_slope: 119, tee_box_type_id: ladies.id, total_yardage_dirty: 0)
dmred.holes.create(hole_number: 1, par_mens: 4, par_ladies: 4, yardage: 231, handicap_mens: 15, handicap_ladies:15)
dmred.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 115, handicap_mens: 11, handicap_ladies: 11)
dmred.holes.create(hole_number: 3, par_mens: 5, par_ladies: 5, yardage: 402, handicap_mens: 1, handicap_ladies: 1)
dmred.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 321, handicap_mens: 3, handicap_ladies: 3)
dmred.holes.create(hole_number: 5, par_mens: 3, par_ladies: 3, yardage: 111, handicap_mens: 13, handicap_ladies: 13)
dmred.holes.create(hole_number: 6, par_mens: 4, par_ladies: 5, yardage: 345, handicap_mens: 9, handicap_ladies: 9)
dmred.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 274, handicap_mens: 7, handicap_ladies: 7)
dmred.holes.create(hole_number: 8, par_mens: 3, par_ladies: 3, yardage: 113, handicap_mens: 17, handicap_ladies: 17)
dmred.holes.create(hole_number: 9, par_mens: 5, par_ladies: 5, yardage: 441, handicap_mens: 5, handicap_ladies: 5)
dmred.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 121, handicap_mens: 18, handicap_ladies: 18)
dmred.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 412, handicap_mens: 10, handicap_ladies: 10)
dmred.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 324, handicap_mens: 4, handicap_ladies: 4)
dmred.holes.create(hole_number: 13, par_mens: 4, par_ladies: 5, yardage: 321, handicap_mens: 2, handicap_ladies: 2)
dmred.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 125, handicap_mens: 6, handicap_ladies: 6)
dmred.holes.create(hole_number: 15, par_mens: 4, par_ladies: 4, yardage: 328, handicap_mens: 14, handicap_ladies: 14)
dmred.holes.create(hole_number: 16, par_mens: 5, par_ladies: 5, yardage: 411, handicap_mens: 8, handicap_ladies: 8)
dmred.holes.create(hole_number: 17, par_mens: 3, par_ladies: 3, yardage: 97, handicap_mens: 16, handicap_ladies: 16)
dmred.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 302, handicap_mens: 12, handicap_ladies: 12)

s = Course.create(name: 'Sidewinder at Gold Canyon Golf Resort', phone_number: '(800) 827-5281', address: '6100 S Kings Ranch Rd', city: 'Gold Canyon', state: 'AZ', zip: '85118', par3: false)
sgold = s.tee_boxes.create(color: 'GOLD', mens_course_rating: 71.4, mens_course_slope: 133, ladies_course_rating: 71.4, ladies_course_slope: 133, tee_box_type_id: mens.id, total_yardage_dirty: 0)
sgold.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 487, handicap_mens: 13, handicap_ladies:13)
sgold.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 251, handicap_mens: 9, handicap_ladies: 9)
sgold.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 400, handicap_mens: 5, handicap_ladies: 5)
sgold.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 147, handicap_mens: 17, handicap_ladies: 17)
sgold.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 352, handicap_mens: 11, handicap_ladies: 11)
sgold.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 523, handicap_mens: 3, handicap_ladies: 3)
sgold.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 177, handicap_mens: 15, handicap_ladies: 15)
sgold.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 417, handicap_mens: 1, handicap_ladies: 1)
sgold.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 392, handicap_mens: 7, handicap_ladies: 7)
sgold.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 165, handicap_mens: 16, handicap_ladies: 16)
sgold.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 511, handicap_mens: 6, handicap_ladies: 6)
sgold.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 435, handicap_mens: 10, handicap_ladies: 10)
sgold.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 14, handicap_ladies: 14)
sgold.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 212, handicap_mens: 8, handicap_ladies: 8)
sgold.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 418, handicap_mens: 4, handicap_ladies: 4)
sgold.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 447, handicap_mens: 2, handicap_ladies: 2)
sgold.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 319, handicap_mens: 18, handicap_ladies: 18)
sgold.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 505, handicap_mens: 12, handicap_ladies: 12)

sblack = s.tee_boxes.create(color: 'BLACK', mens_course_rating: 69.3, mens_course_slope: 128, ladies_course_rating: 69.3, ladies_course_slope: 128, tee_box_type_id: mens.id, total_yardage_dirty: 0)
sblack.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 477, handicap_mens: 13, handicap_ladies:13)
sblack.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 180, handicap_mens: 9, handicap_ladies: 9)
sblack.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 378, handicap_mens: 5, handicap_ladies: 5)
sblack.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 133, handicap_mens: 17, handicap_ladies: 17)
sblack.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 338, handicap_mens: 11, handicap_ladies: 11)
sblack.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 511, handicap_mens: 3, handicap_ladies: 3)
sblack.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 163, handicap_mens: 15, handicap_ladies: 15)
sblack.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 372, handicap_mens: 1, handicap_ladies: 1)
sblack.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 7, handicap_ladies: 7)
sblack.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 154, handicap_mens: 16, handicap_ladies: 16)
sblack.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 499, handicap_mens: 6, handicap_ladies: 6)
sblack.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 404, handicap_mens: 10, handicap_ladies: 10)
sblack.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 364, handicap_mens: 14, handicap_ladies: 14)
sblack.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 191, handicap_mens: 8, handicap_ladies: 8)
sblack.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 403, handicap_mens: 4, handicap_ladies: 4)
sblack.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 426, handicap_mens: 2, handicap_ladies: 2)
sblack.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 294, handicap_mens: 18, handicap_ladies: 18)
sblack.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 475, handicap_mens: 12, handicap_ladies: 12)

sblue = s.tee_boxes.create(color: 'BLUE', mens_course_rating: 66.7, mens_course_slope: 120, ladies_course_rating: 66.7, ladies_course_slope: 120, tee_box_type_id: mens.id, total_yardage_dirty: 0)
sblue.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 420, handicap_mens: 13, handicap_ladies:13)
sblue.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 160, handicap_mens: 9, handicap_ladies: 9)
sblue.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 342, handicap_mens: 5, handicap_ladies: 5)
sblue.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 127, handicap_mens: 17, handicap_ladies: 17)
sblue.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 309, handicap_mens: 11, handicap_ladies: 11)
sblue.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 444, handicap_mens: 3, handicap_ladies: 3)
sblue.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 150, handicap_mens: 15, handicap_ladies: 15)
sblue.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 347, handicap_mens: 1, handicap_ladies: 1)
sblue.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 353, handicap_mens: 7, handicap_ladies: 7)
sblue.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 137, handicap_mens: 16, handicap_ladies: 16)
sblue.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 484, handicap_mens: 6, handicap_ladies: 6)
sblue.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 362, handicap_mens: 10, handicap_ladies: 10)
sblue.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 323, handicap_mens: 14, handicap_ladies: 14)
sblue.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 180, handicap_mens: 8, handicap_ladies: 8)
sblue.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 394, handicap_mens: 4, handicap_ladies: 4)
sblue.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 370, handicap_mens: 2, handicap_ladies: 2)
sblue.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 279, handicap_mens: 18, handicap_ladies: 18)
sblue.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 454, handicap_mens: 12, handicap_ladies: 12)

swhite = s.tee_boxes.create(color: 'WHITE', mens_course_rating: 64.6, mens_course_slope: 114, ladies_course_rating: 70.3, ladies_course_slope: 124, tee_box_type_id: both.id, total_yardage_dirty: 0)
swhite.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 401, handicap_mens: 13, handicap_ladies:13)
swhite.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 140, handicap_mens: 9, handicap_ladies: 9)
swhite.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 315, handicap_mens: 5, handicap_ladies: 5)
swhite.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 115, handicap_mens: 17, handicap_ladies: 17)
swhite.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 260, handicap_mens: 11, handicap_ladies: 11)
swhite.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 414, handicap_mens: 3, handicap_ladies: 3)
swhite.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 108, handicap_mens: 15, handicap_ladies: 15)
swhite.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 296, handicap_mens: 1, handicap_ladies: 1)
swhite.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 278, handicap_mens: 7, handicap_ladies: 7)
swhite.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 116, handicap_mens: 16, handicap_ladies: 16)
swhite.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 464, handicap_mens: 6, handicap_ladies: 6)
swhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 350, handicap_mens: 10, handicap_ladies: 10)
swhite.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 303, handicap_mens: 14, handicap_ladies: 14)
swhite.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 170, handicap_mens: 8, handicap_ladies: 8)
swhite.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 370, handicap_mens: 4, handicap_ladies: 4)
swhite.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 311, handicap_mens: 2, handicap_ladies: 2)
swhite.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 233, handicap_mens: 18, handicap_ladies: 18)
swhite.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 420, handicap_mens: 12, handicap_ladies: 12)

ssilver = s.tee_boxes.create(color: 'SILVER', mens_course_rating: 63.7, mens_course_slope: 111, ladies_course_rating: 69.5, ladies_course_slope: 123, tee_box_type_id: both.id, total_yardage_dirty: 0)
swhite.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 378, handicap_mens: 13, handicap_ladies:13)
swhite.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 135, handicap_mens: 9, handicap_ladies: 9)
swhite.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 300, handicap_mens: 5, handicap_ladies: 5)
swhite.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 109, handicap_mens: 17, handicap_ladies: 17)
swhite.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 257, handicap_mens: 11, handicap_ladies: 11)
swhite.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 404, handicap_mens: 3, handicap_ladies: 3)
swhite.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 108, handicap_mens: 15, handicap_ladies: 15)
swhite.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 287, handicap_mens: 1, handicap_ladies: 1)
swhite.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 280, handicap_mens: 7, handicap_ladies: 7)
swhite.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 117, handicap_mens: 16, handicap_ladies: 16)
swhite.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 449, handicap_mens: 6, handicap_ladies: 6)
swhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 342, handicap_mens: 10, handicap_ladies: 10)
swhite.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 291, handicap_mens: 14, handicap_ladies: 14)
swhite.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 162, handicap_mens: 8, handicap_ladies: 8)
swhite.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 367, handicap_mens: 4, handicap_ladies: 4)
swhite.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 376, handicap_mens: 2, handicap_ladies: 2)
swhite.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 233, handicap_mens: 18, handicap_ladies: 18)
swhite.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 416, handicap_mens: 12, handicap_ladies: 12)

sred = s.tee_boxes.create(color: 'RED', mens_course_rating: 65.8, mens_course_slope: 112, ladies_course_rating: 65.8, ladies_course_slope: 112, tee_box_type_id: ladies.id, total_yardage_dirty: 0)
sred.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 344, handicap_mens: 3, handicap_ladies:3)
sred.holes.create(hole_number: 2, par_mens: 3, par_ladies: 3, yardage: 123, handicap_mens: 13, handicap_ladies: 9)
sred.holes.create(hole_number: 3, par_mens: 4, par_ladies: 4, yardage: 237, handicap_mens: 5, handicap_ladies: 5)
sred.holes.create(hole_number: 4, par_mens: 3, par_ladies: 3, yardage: 75, handicap_mens: 17, handicap_ladies: 17)
sred.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 210, handicap_mens: 11, handicap_ladies: 11)
sred.holes.create(hole_number: 6, par_mens: 5, par_ladies: 5, yardage: 359, handicap_mens: 1, handicap_ladies: 1)
sred.holes.create(hole_number: 7, par_mens: 3, par_ladies: 3, yardage: 95, handicap_mens: 15, handicap_ladies: 15)
sred.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 211, handicap_mens: 9, handicap_ladies: 9)
sred.holes.create(hole_number: 9, par_mens: 4, par_ladies: 4, yardage: 245, handicap_mens: 7, handicap_ladies: 7)
sred.holes.create(hole_number: 10, par_mens: 3, par_ladies: 3, yardage: 104, handicap_mens: 18, handicap_ladies: 18)
sred.holes.create(hole_number: 11, par_mens: 5, par_ladies: 5, yardage: 440, handicap_mens: 4, handicap_ladies: 4)
sred.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 301, handicap_mens: 10, handicap_ladies: 10)
sred.holes.create(hole_number: 13, par_mens: 4, par_ladies: 4, yardage: 277, handicap_mens: 12, handicap_ladies: 12)
sred.holes.create(hole_number: 14, par_mens: 3, par_ladies: 3, yardage: 151, handicap_mens: 16, handicap_ladies: 16)
sred.holes.create(hole_number: 15, par_mens: 4, par_ladies: 5, yardage: 354, handicap_mens: 6, handicap_ladies: 6)
sred.holes.create(hole_number: 16, par_mens: 4, par_ladies: 4, yardage: 275, handicap_mens: 8, handicap_ladies: 8)
sred.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 178, handicap_mens: 14, handicap_ladies: 14)
sred.holes.create(hole_number: 18, par_mens: 5, par_ladies: 5, yardage: 334, handicap_mens: 2, handicap_ladies: 2)

ls = Course.create(name: 'Las Sendas Golf Club', phone_number: '(800) 827-5281', address: '7555 East Eagle Crest Drive', city: 'Mesa', state: 'AZ', zip: '85207', par3: false)
lssilver = ls.tee_boxes.create(color: 'SILVER', mens_course_rating: 73.1, mens_course_slope: 144, ladies_course_rating: 73.1, ladies_course_slope: 144, tee_box_type_id: mens.id, total_yardage_dirty: 6825)

lsblack = ls.tee_boxes.create(color: 'BLACK', mens_course_rating: 72.0, mens_course_slope: 139, ladies_course_rating: 72.0, ladies_course_slope: 139, tee_box_type_id: mens.id, total_yardage_dirty: 6661)

lsgold = ls.tee_boxes.create(color: 'GOLD', mens_course_rating: 71.2, mens_course_slope: 133, ladies_course_rating: 71.2, ladies_course_slope: 133, tee_box_type_id: mens.id, total_yardage_dirty: 6327)

lsblue = ls.tee_boxes.create(color: 'BLUE', mens_course_rating: 69.4, mens_course_slope: 129, ladies_course_rating: 75.4, ladies_course_slope: 137, tee_box_type_id: both.id, total_yardage_dirty: 5957)

lswhite = ls.tee_boxes.create(color: 'WHITE', mens_course_rating: 65.7, mens_course_slope: 121, ladies_course_rating: 72.2, ladies_course_slope: 133, tee_box_type_id: both.id, total_yardage_dirty: 5422)

lscopper = ls.tee_boxes.create(color: 'COPPER', mens_course_rating: 70.5, mens_course_slope: 128, ladies_course_rating: 70.5, ladies_course_slope: 128, tee_box_type_id: ladies.id, total_yardage_dirty: 5064)