# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

TournamentType.create(tournament_type: 'INDIVIDUAL')
TournamentType.create(tournament_type: 'TEAM SCRAMBLE')
#TournamentType.create(tournament_type: 'TEAM')
tt = TournamentType.create(tournament_type: 'TWO-TEAM')

RoundType.create(round_type: '2-BALL')
RoundType.create(round_type: '4-BALL')
RoundType.create(round_type: 'HEAD-TO-HEAD')

fresca2012 = tt.tournaments.create(title: 'FRESCA 2012', subtitle: '', tournament_date: '6/1/2012', location: 'Pebble Beach', handicap: true, male_players: true, female_players: false, started: true, complete: true)
fresca2012.teams.create(name: 'Unnamed', team_number: 1)
fresca2012.teams.create(name: 'Unnamed', team_number: 2)

fresca2013 = tt.tournaments.create(title: 'FRESCA 2013', subtitle: 'Pining for You', tournament_date: '6/1/2013', location: 'Torrey Pines', handicap: true, male_players: true, female_players: false, started: true, complete: false)
fresca2013.teams.create(name: 'Unnamed', team_number: 1)
fresca2013.teams.create(name: 'Unnamed', team_number: 2)

fresca2014 = tt.tournaments.create(title: 'FRESCA 2014', subtitle: 'Birdies and Bogies', tournament_date: '6/1/2014', location: 'Bandon Dunes', handicap: true, male_players: true, female_players: false, started: false, complete: false)
fresca2014.teams.create(name: 'Unnamed', team_number: 1)
fresca2014.teams.create(name: 'Unnamed', team_number: 2)

Player.create(first_name: 'Jamie', last_name: 'Gulick', nickname: 'Lurch', handicap: 24.7, email: 'jamie.gulick@gmail.com', username: 'jamie.gulick@gmail.com', password: 'password')
Player.create(first_name: 'Brian', last_name: 'Cordyack', nickname: 'Yack', handicap: 19.2, email: 'username@server.com', username: 'bcordyack', password: 'password')
Player.create(first_name: 'Dan', last_name: 'Shomaker', nickname: 'Shomo', handicap: 13.3, email: 'username@server.com', username: 'dshomaker', password: 'password')
Player.create(first_name: 'Jeff', last_name: 'Hall', nickname: 'Jefe', handicap: 10, email: 'username@server.com', username: 'jhall', password: 'password')
Player.create(first_name: 'Matt', last_name: 'Foster', nickname: 'Fos', handicap: 7.3, email: 'username@server.com', username: 'mfoster', password: 'password')
Player.create(first_name: 'Chris', last_name: 'Hawkins', nickname: 'CHawk', handicap: 29.4, email: 'username@server.com', username: 'chawkins', password: 'password')
Player.create(first_name: 'Greg', last_name: 'Bane', nickname: 'Bane', handicap: 20.5, email: 'username@server.com', username: 'gbane', password: 'password')
Player.create(first_name: 'Michael', last_name: 'Belinkie', handicap: 31.7, email: 'username@server.com', username: 'mbelinkie', password: 'password')
Player.create(first_name: 'Matt', last_name: 'Zalubowski', nickname: 'Zow', handicap: 19.2, email: 'username@server.com', username: 'mzalubowski', password: 'password')
Player.create(first_name: 'Jason', last_name: 'Elam', handicap: 23, email: 'username@server.com', username: 'jelam', password: 'password')
Player.create(first_name: '11', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player11', password: 'password')
Player.create(first_name: '12', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player12', password: 'password')
Player.create(first_name: '13', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player13', password: 'password')
Player.create(first_name: '14', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player14', password: 'password')
Player.create(first_name: '15', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player15', password: 'password')
Player.create(first_name: '16', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player16', password: 'password')
Player.create(first_name: '17', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player17', password: 'password')
Player.create(first_name: '18', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player18', password: 'password')
Player.create(first_name: '19', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player19', password: 'password')
Player.create(first_name: '20', last_name: 'Player', handicap: 25.0, email: 'player11@server.com', username: 'player20', password: 'password')

mens = TeeBoxType.create(tee_box_type: 'MENS')
ladies = TeeBoxType.create(tee_box_type: 'LADIES')
TeeBoxType.create(tee_box_type: 'BOTH')

gc = Course.create(name: 'Goose Creek Golf Club', phone_number: '(703) 729-2500', address: '43001 Golf Club Road', city: 'Leesburg', state: 'VA', zip: '20175', par3: false)
gcblue = gc.tee_boxes.create(color: 'BLUE', mens_course_rating: 71.8, mens_course_slope: 130, ladies_course_rating: 71.8, ladies_course_slope: 130, tee_box_type_id: mens.id, total_yardage_dirty: 6410)
gcblue.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 475, handicap_mens: 3, handicap_ladies:3)
gcblue.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 387, handicap_mens: 9, handicap_ladies: 9)
gcblue.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 169, handicap_mens: 11, handicap_ladies: 11)
gcblue.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 377, handicap_mens: 13, handicap_ladies: 13)
gcblue.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 376, handicap_mens: 5, handicap_ladies: 5)
gcblue.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 411, handicap_mens: 1, handicap_ladies: 1)
gcblue.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 308, handicap_mens: 17, handicap_ladies: 17)
gcblue.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 322, handicap_mens: 15, handicap_ladies: 15)
gcblue.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 193, handicap_mens: 7, handicap_ladies: 7)
gcblue.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 329, handicap_mens: 16, handicap_ladies: 16)
gcblue.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 429, handicap_mens: 4, handicap_ladies: 4)
gcblue.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 417, handicap_mens: 2, handicap_ladies: 2)
gcblue.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 236, handicap_mens: 10, handicap_ladies: 10)
gcblue.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 496, handicap_mens: 14, handicap_ladies: 14)
gcblue.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 494, handicap_mens: 12, handicap_ladies: 12)
gcblue.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 227, handicap_mens: 6, handicap_ladies: 6)
gcblue.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 425, handicap_mens: 8, handicap_ladies: 8)
gcblue.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 339, handicap_mens: 18, handicap_ladies: 18)

gcwhite = gc.tee_boxes.create(color: 'WHITE', mens_course_rating: 69.6, mens_course_slope: 125, ladies_course_rating: 69.6, ladies_course_slope: 125, tee_box_type_id: mens.id, total_yardage_dirty: 5937)
gcwhite.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 471, handicap_mens: 3, handicap_ladies:3)
gcwhite.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 366, handicap_mens: 9, handicap_ladies: 9)
gcwhite.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 143, handicap_mens: 11, handicap_ladies: 11)
gcwhite.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 346, handicap_mens: 13, handicap_ladies: 13)
gcwhite.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 370, handicap_mens: 5, handicap_ladies: 5)
gcwhite.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 393, handicap_mens: 1, handicap_ladies: 1)
gcwhite.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 279, handicap_mens: 17, handicap_ladies: 17)
gcwhite.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 297, handicap_mens: 15, handicap_ladies: 15)
gcwhite.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 155, handicap_mens: 7, handicap_ladies: 7)
gcwhite.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 321, handicap_mens: 16, handicap_ladies: 16)
gcwhite.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 410, handicap_mens: 4, handicap_ladies: 4)
gcwhite.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 2, handicap_ladies: 2)
gcwhite.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 189, handicap_mens: 10, handicap_ladies: 10)
gcwhite.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 449, handicap_mens: 14, handicap_ladies: 14)
gcwhite.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 484, handicap_mens: 12, handicap_ladies: 12)
gcwhite.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 182, handicap_mens: 6, handicap_ladies: 6)
gcwhite.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 375, handicap_mens: 8, handicap_ladies: 8)
gcwhite.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 332, handicap_mens: 18, handicap_ladies: 18)

gcred = gc.tee_boxes.create(color: 'RED', mens_course_rating: 70.7, mens_course_slope: 123, ladies_course_rating: 70.7, ladies_course_slope: 123, tee_box_type_id: ladies.id, total_yardage_dirty: 5170)
gcred.holes.create(hole_number: 1, par_mens: 5, par_ladies: 5, yardage: 391, handicap_mens: 9, handicap_ladies:9)
gcred.holes.create(hole_number: 2, par_mens: 4, par_ladies: 4, yardage: 324, handicap_mens: 3, handicap_ladies: 3)
gcred.holes.create(hole_number: 3, par_mens: 3, par_ladies: 3, yardage: 111, handicap_mens: 17, handicap_ladies: 17)
gcred.holes.create(hole_number: 4, par_mens: 4, par_ladies: 4, yardage: 323, handicap_mens: 1, handicap_ladies: 1)
gcred.holes.create(hole_number: 5, par_mens: 4, par_ladies: 4, yardage: 335, handicap_mens: 7, handicap_ladies: 7)
gcred.holes.create(hole_number: 6, par_mens: 4, par_ladies: 4, yardage: 292, handicap_mens: 5, handicap_ladies: 5)
gcred.holes.create(hole_number: 7, par_mens: 4, par_ladies: 4, yardage: 272, handicap_mens: 15, handicap_ladies: 15)
gcred.holes.create(hole_number: 8, par_mens: 4, par_ladies: 4, yardage: 244, handicap_mens: 13, handicap_ladies: 13)
gcred.holes.create(hole_number: 9, par_mens: 3, par_ladies: 3, yardage: 144, handicap_mens: 11, handicap_ladies: 11)
gcred.holes.create(hole_number: 10, par_mens: 4, par_ladies: 4, yardage: 270, handicap_mens: 14, handicap_ladies: 14)
gcred.holes.create(hole_number: 11, par_mens: 4, par_ladies: 4, yardage: 350, handicap_mens: 2, handicap_ladies: 2)
gcred.holes.create(hole_number: 12, par_mens: 4, par_ladies: 4, yardage: 312, handicap_mens: 6, handicap_ladies: 6)
gcred.holes.create(hole_number: 13, par_mens: 3, par_ladies: 3, yardage: 155, handicap_mens: 16, handicap_ladies: 16)
gcred.holes.create(hole_number: 14, par_mens: 5, par_ladies: 5, yardage: 428, handicap_mens: 10, handicap_ladies: 10)
gcred.holes.create(hole_number: 15, par_mens: 5, par_ladies: 5, yardage: 433, handicap_mens: 8, handicap_ladies: 8)
gcred.holes.create(hole_number: 16, par_mens: 3, par_ladies: 3, yardage: 159, handicap_mens: 12, handicap_ladies: 12)
gcred.holes.create(hole_number: 17, par_mens: 4, par_ladies: 4, yardage: 308, handicap_mens: 4, handicap_ladies: 4)
gcred.holes.create(hole_number: 18, par_mens: 4, par_ladies: 4, yardage: 319, handicap_mens: 18, handicap_ladies: 18)